default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: code_central
  password: code_central
  host: localhost

development:
  <<: *default
  database: code_central_development

test:
  <<: *default
  username: <%= ENV["TRAVIS"] ? "travis" : "code_central" %>
  password: <%= ENV["TRAVIS"] ? "" : "code_central" %>
  database: code_central_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
