# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29ecf1a99b7a5b023e1efa775ed1055f5825bf046ff6e1066e102d68bf8d62d3512f19f7ae71b70b35913cc5deaa48b5a73a19e508d9b0791be3319ad9a9be19

test:
  secret_key_base: bd868ed4021e80db71f1cba11a5a1344fd07aa15d04e469492bfc7be2300e6a0ee68867f17477fd9100cd420751d17ac4ea78619ba65bf80994136fc0f1fbcd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
